# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_newideabox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('a', 'all')], max_length=1),
        ),
        migrations.AlterField(
            model_name='area',
            name='gender_img_url',
            field=models.CharField(default='/static/images/gender', max_length=100),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='attribute_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='market',
            name='close_time',
            field=models.DateTimeField(verbose_name='close time'),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_time',
            field=models.DateTimeField(verbose_name='open time'),
        ),
        migrations.AlterField(
            model_name='newideabox',
            name='attribute_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('n', 'none')], max_length=1),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='estimate_time',
            field=models.DateTimeField(verbose_name='estimate time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='close_time',
            field=models.DateTimeField(verbose_name='close time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='open_time',
            field=models.DateTimeField(verbose_name='open time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='security',
            name='attribute_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='securityresult',
            name='attribute_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='securityresult',
            name='estimate_time',
            field=models.DateTimeField(verbose_name='estimate_time'),
        ),
        migrations.AlterField(
            model_name='shopfigure',
            name='img_url',
            field=models.CharField(default='/static/images/Shops', max_length=100),
        ),
    ]
